// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL0OYxT3zTXwkWtL1K_I9KJoDiP4rVtmw',
    appId: '1:69439907484:web:fb615751649f2c130b6f59',
    messagingSenderId: '69439907484',
    projectId: 'multi-vendor-e-commerce-ec832',
    authDomain: 'multi-vendor-e-commerce-ec832.firebaseapp.com',
    storageBucket: 'multi-vendor-e-commerce-ec832.firebasestorage.app',
    measurementId: 'G-MSPXKVE7DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdiYfL-4MVo5pd29aTwE3boSU6j3cNAEQ',
    appId: '1:69439907484:android:2a23417b8d6b30180b6f59',
    messagingSenderId: '69439907484',
    projectId: 'multi-vendor-e-commerce-ec832',
    storageBucket: 'multi-vendor-e-commerce-ec832.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO3R1AYCSa9xgWEcxFR0uSeueboZgkZP0',
    appId: '1:69439907484:ios:97ec4af1b17a65ec0b6f59',
    messagingSenderId: '69439907484',
    projectId: 'multi-vendor-e-commerce-ec832',
    storageBucket: 'multi-vendor-e-commerce-ec832.firebasestorage.app',
    iosBundleId: 'com.example.multiVendorECommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO3R1AYCSa9xgWEcxFR0uSeueboZgkZP0',
    appId: '1:69439907484:ios:97ec4af1b17a65ec0b6f59',
    messagingSenderId: '69439907484',
    projectId: 'multi-vendor-e-commerce-ec832',
    storageBucket: 'multi-vendor-e-commerce-ec832.firebasestorage.app',
    iosBundleId: 'com.example.multiVendorECommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL0OYxT3zTXwkWtL1K_I9KJoDiP4rVtmw',
    appId: '1:69439907484:web:f629d744a396c4d10b6f59',
    messagingSenderId: '69439907484',
    projectId: 'multi-vendor-e-commerce-ec832',
    authDomain: 'multi-vendor-e-commerce-ec832.firebaseapp.com',
    storageBucket: 'multi-vendor-e-commerce-ec832.firebasestorage.app',
    measurementId: 'G-PZQ6RWVGPP',
  );

}